### ISSUE TITLE
[FEATURE] Network universal experience

### ISSUE THREAD

**Issue by george112n** [BuildTheEarth/BuildTeamTools#18]
This issue regards any additional changes which need to be made to allow network specific features to be implemented to the plugin.

1. The plugin must connect to a database which holds information relevant for universal features (warps, user nav preferences etc)
2. The plugin must have some way of knowing on startup whether it is connected to the network or not

**Comment by Nudelsuppe42** [comment]
2 should already be implemented.

**Comment by frikandelworst** [comment]
1 should probably always go trough an API. We can't share database credentials with all servers who install this plugin as that poses a security risk.

**Comment by MineFact** [comment]
There is two ways how to sync universal data with the BuildTeamTools plugin.

1. The proxy reads/writes the data from/to a database and sends the data to the BuildTeamTools plugin on request via the Plugin Messaging Channel

2. An API is made that the BuildTeamTools plugin can request data from. If this method is chosen its probably best to integrate it into an existing API since we already have some up and running. Another API would be a bit too much.

**Comment by Nudelsuppe42** [comment]
Which would be the plot system or website api.

**Comment by frikandelworst** [comment]
This is implemented/obsolete.
